### ISSUE TITLE
How do I deploy elf files to the cubes, and is it possible to use Sifteo Sync without a log in?

### ISSUE THREAD

**Issue by DoctorMikeReddy** [sifteo/thundercracker#3]
Can you explain how to deploy elf files to the actual hardware, and can Sifteo Sync (or Sift Runner) be used without the log in to the now non-existent servers? I'm asking because I am trying to determine whether purchasing this old hardware is worthwhile.

**Comment by scanlime** [comment]
The "swiss" tool in the SDK can be used to manage ELF files on the actual
hardware, but AFAIK you won't have a way to connect to the store. So, the
old hardware is still usable for homebrew games or games you've obtained
through some other means, but I don't think there's a way to buy games any
longer.

-m

**Comment by DoctorMikeReddy** [comment]
Thank you. I just managed to trawl through documentation and found the swiss reference. I'm also interested in the 'original' Sifteo Cubes (much easier to find right now on the Internet, bizarrely), and pretty sure that the new deployment method won't work with the old SDK; I'm trawling through that set of documentation too right now. I've found a way to bypass the login screen - still no guarantee that this will allow me to use SiftRunner properly - by clicking Help from the Toolbar (on a Mac), as this then allows me to access the My Games (empty of course) and the Store Tab (not working, obviously) and then the Toolbar menu items. I guess I will have to experiment with how functional this all is once I get some Sifteos. As to sourcing the original games, I'm going to ask the developers (at the new company) if they would be willing to release these. Alternatives can only be trying to find people who backed up the games when they were released for free in the Summer of last year. I mostly want the cubes for my own development - and am kicking myself for never having heard of them before this month! - so it isn't a breaker not to have access to original titles, but it would be great to have them open sourced too TBH so they aren't lost to the Ether. Even if people could run these in emulation it would keep the platform alive. It was such a shame that it died the way it did.

**Comment by skunkofdoom** [comment]
Did you ever find a source for the software for sifteo?

**Comment by DoctorMikeReddy** [comment]
The software is available open source for development on the Internet:. The games, on the other hand, are not as freely available. I have been given many of the 2nd Gen titles, which can be deployed using the dev software for installing on cubes - thanks to the developer David Merrill - and am in the process of setting up an archive for other owners. However, I have only made progress with the original Sync software for the Gen 1 cubes - these, along with the 2nd gen required the Sifteo server, which no longer exists - and then only on the PC version; this involved creating and hacking a registry entry, as well as analysing a zip archive of a working directory from Eric Liao, one of the main developers.
My plan is to get Sifteo Sync working as well as I got SiftRunner (the gen 1 software) going, although this is less important; SiftRunner had a mediating role, because the software ran on the parent machine, and getting SiftRunner was necessary for the Creativity Kit, which was a really cool modifiable game engine, which the V2 cubes never got; although I discussed this with the developers and it could have been done, using low level comms between PC and the more autonomous 2nd gen devices.
Sifteo Sync would just make installing software on the cubes, which were designed to run more independently, on the base station a bit easier. As I said, you can use Swiss, a tool in the dev chain, to install software once you have it (or have written it). However, I only have v1 cubes for testing right now. A friend has offered to lend me some 2nd gen cubes, but if you want the game software, Steven, PM me and I will provide to you what I have right now; with grateful thanks to David for giving them to me, and allowing me to redistribute to other interested Sifteo owners.
As you can imagine, I am doing this out of a love for this unique device, and in my spare time. Eventually, I will ask for small donations towards hosting files and continuing to research software in a world where the original servers no longer exist. I've had one donation from a grateful 1st gen user who 'playtested' my gen 1 software mods to confirm that this worked to restore both missing games and the creativity kit functionality.

**Comment by DoctorMikeReddy** [comment]
Recently posted on reddit:
https://www.reddit.com/r/sifteo/comments/5rv33t/sifteo_resurrected/
"I’d like to humbly announce the following page: http://doctormikereddy.com/sifteo-resurrecting-a-legend/ which contains a (growing) number of resources for those people lucky enough to own (or unlucky enough to have recently bought second hand) the wonderful Sifteo Cubes; either V1 with the dongle, or V2 with the base station. On that site you can download the software (with hacks to get it to run without the long gone sifteo.com server), all the games officially released, and SDKs to make your own, either for physical cubes or for the simulators. There will be more to come, including how to set up the SDKs - for now there are a few sites still out there on Google - and how to make games for this unique platform. Thank you for your patience!"
DoctorMike

**Comment by mmumma** [comment]
Hi DoctorMike,  I found some V1 cubes and have been trying to make the work through my iMac, I've installed the files, and I still can't get it not to ask for connection to the server to login.  I tried the defaults read ~/Library/Preferences/com.sifteo.Sync.plist command but it told me the file doesn't exist (which in fact it doesn't).  Just wondering if there are any further tricks to this.  Thanks very much.

**Comment by DoctorMikeReddy** [comment]
Sorry to take so long to respond. If you contact me via my blog - link above - or by email, you will get quicker responses, as this isn't my git repo; I just posted here once :-)
You need to go to my web site and download the relevant files, which will include the preference file and install it in the location you specify.
