### ISSUE TITLE
Open letter to Sifteo Devs

### ISSUE THREAD

**Issue by DoctorMikeReddy** [sifteo/thundercracker#4]
[Going to post this here, on bitBucket, and try to email relevant ex-Sifteo people directly, if I can, so please accept my apologies if you get this more than once. I know you've all moved on to 3D Robotics now, and this is ancient history; strange how a couple of years is enough for things to be obscured by virtual dust...]
Hello,
My name is Dr. Mike Reddy, and I am a UK academic researcher in games, toys and gadgets. I've JUST recently acquired a 'new' set of the original Sifteo cubes - by way of a Seattle thrift shop sale (a long story!) - but, of course, support for these is lacking compared to the 2nd generation cubes. At least they got an open source parting shot from yourselves, which if not complete is still enough to do some development work. However, the original cubes seems to require a log in, and I have been unable to get the Siftulator simulator working with Siftrunner.

It is possible to get past the log in page by choosing Help from the Toolbar, then clicking on My Games, but when I try to run an app from the dev kit, it never seems to load in Siftrunner for me to deploy to Siftulator; the actual cubes are on their way from the US, so I've not been able to try them with the actual hardware yet. It is, of course, possible that not getting the apps to load in Siftrunner requires an unlock by connecting with physical cubes, but I suspect it is more likely to be due to the lack of the remote server. At this stage, it is possible that I won't be able to easily develop for these cubes, so I am contacting you to see if you could be of some help.

I've been doing a lot of digging, including a bit of archive.org trawling through the original Sifteo web site, along with reaching out to people who developed for both versions of Sifteo, to try to piece together documentation and software for the 'originals' as much as the later incarnation. Currently, there are some obvious gaps - only the SDK for the 2nd version is easily available - but I've managed to get the Sifteo Sync beta 0.9.10 for Mac, the last version of SiftRunner for Mac and PC, and the original SDK for v1 Cubes; mostly from the WayBack Machine archive, with a little help from redditors :-) However, I don't have the PC (or any of the Linux incarnations) of Sifteo Sync , and most importantly, all of the games originally offered on the Sifteo web site are  gone :-(

I am aware that they were all made 'free' towards the end of the product support phase (mid 2015), so I missed my opportunity to get hold of some of the existing apps created for either set of cubes. Amazingly, I only recently became aware of these things - a chance view of an old Extra Credits YouTube video, where they were mentioned - but in my defence the mid 2010s were a very busy time for me, with me fighting just to keep my job, during a difficult merger with another university, and games/gaming (my main teaching area before and since) were the last things on my mind. 

Although the product, and the company are now a memory, I think that Sifteo Cubes were an amazing idea, truly before their time! To that end, I would like to find any way possible to archive and advocate the importance of these clever little cubes as a historical milestone. Any help you can provide would be gratefully appreciated. For example, having open source access to Siftrunner and SifteoSync would allow me to modify them, so they did not need remote server log ins. I am aware from a 2011 Android presentation that at least a test app for tablets could communicate with the original cubes; access to even this test code would provide a great stepping stone for resurrecting the v1 cubes. Of course, it would be excellent if executables (if not the whole source) for some or all of the games, in parallel with a decoupled Siftrunner, would allow these to be run in emulation even if interested people did not have access to the hardware. Similarly for the v2 cubes, although the open source sdk allows homebrewed apps to run already. Seeing the source code, etc, for the v2 games would also be of significant historical interest. What amazes me, apart from the sadly unsuccessful demise of the sifteo, was how quickly it seemed to disappear from the Internet Consciousness; I'd like to reverse that trend if at all possible.

It is possible that you are not in any position to be able to help me, so I might have to keep reaching out to other Sifteo owners and/or attempt reverse engineering the PC/Mac software for controlling the Sifteos, for a full rewrite - what I'm now going to call "Softeo" - but I'm determined to resurrect my old Sifteos!. Although this might be quite challenging, I have a vested interest: I have some original cubes on their way from a friend in the States! I would love to get a copy of the v2 cubes one day, but they are bizarrely scarce; maybe one day if I am lucky. 

Either way, with the v2 SDK and the more polished emulator, I am going to be setting student coursework and projects using Sifteo, as I don't think all the nuances of this unique platform were really fully explored. They really were ahead of their time. Amazing to think that they evolved from a 2009 project (I loved the TED talk at the time, but never realised they had been commercially released; so many miraculous things come out of MIT, etc, that never see the light of day for the rest of us). Whatever happens, how ever you can help, I'd like to thank you for creating a wonderful idea.

Dr. Mike Reddy
Course Tutor in Computer Games Development
University of South Wales, UK

**Comment by digitalhoax** [comment]
Just as a quick follow up to this post, anyone who stumbles upon it might check the excellent work Mike has done to gather files and support on his page at http://doctormikereddy.com/sifteo-resurrecting-a-legend/#download-stuff

**Comment by DoctorMikeReddy** [comment]
Thank you. I just received a new donation that allowed me to up my V2 hardware to 15 cubes (or three sets of five cubes and base stations), and have some good news regarding some missing brochure files and graphics, which should be going up on the site soon.
