### ISSUE TITLE
Linking error when building launcher

### ISSUE THREAD

**Issue by Green92** [sifteo/thundercracker#5]
Hi,

I've tried to build the project for 2 weeks, and today I'm requiring your help.
The process stop because of a Slinky error.

The displayed message is :
`taking address of undefined symbol : "_call_$"`

I've tried both on linux (64) and windows and the result is the same.

I am far from beeing a cross-compilation expert, and I can't assert nothing about the origin of the problem.
Maybe some of the provided binaries are outdated.

I hope you to see this issue one day.

Green

**Comment by Green92** [comment]
I forgot to remind it happend while building the Launcher project.
I've also tried to build examples and the same error occurs...

**Comment by blkf2016** [comment]
I encountered the same problem. 
Tools used for compiling:
OS: gentoo
gcc: 4.9.4 
binutils: 2.26
glibc: 2.23
arm toolchain:  gcc-arm-none-eabi-4_9-2015q3-20150921

**Comment by blkf2016** [comment]
This issue is resolved by changing gcc version to 4.6.3.

**Comment by DoctorMikeReddy** [comment]
Close now?

**Comment by Green92** [comment]
Yes it is, my apoligies for the slight delay !
