### ISSUE TITLE
how to generate bootloader.bin?

### ISSUE THREAD

**Issue by crazyuav** [sifteo/thundercracker#9]
hi,

I've tried to build the project with commod "make BOOTLOADABLE=1",but there is no bootloader.bin or bootloader.elf generate.

Any problem with commod? and how to generate bootloader.bin

I hope you to see this issue one day

**Comment by ghost** [comment]
The boot loader is a separate build, the "bootloadable" flag just makes a
version of the main firmware that's compatible with the boot loader. I
forget the details but there should be a makefile for that separately
